/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InternalAppRouteRouteImport } from './routes/_internal-app/route'
import { Route as DiffReviewAgentInstanceIdRouteImport } from './routes/diff-review/$agentInstanceId'
import { Route as InternalAppHistoryRouteImport } from './routes/_internal-app/history'
import { Route as InternalAppDownloadsRouteImport } from './routes/_internal-app/downloads'
import { Route as InternalAppClearDataRouteImport } from './routes/_internal-app/clear-data'
import { Route as InternalAppBrowsingSettingsRouteImport } from './routes/_internal-app/browsing-settings'
import { Route as InternalAppAgentSettingsRouteImport } from './routes/_internal-app/agent-settings'
import { Route as InternalAppAccountRouteImport } from './routes/_internal-app/account'
import { Route as InternalAppAboutRouteImport } from './routes/_internal-app/about'
import { Route as InternalAppBrowsingSettingsIndexRouteImport } from './routes/_internal-app/browsing-settings.index'
import { Route as InternalAppAgentSettingsIndexRouteImport } from './routes/_internal-app/agent-settings.index'
import { Route as InternalAppBrowsingSettingsWebsitePermissionsRouteImport } from './routes/_internal-app/browsing-settings.website-permissions'
import { Route as InternalAppAgentSettingsModelsRouteImport } from './routes/_internal-app/agent-settings.models'
import { Route as InternalAppAgentSettingsCustomProvidersRouteImport } from './routes/_internal-app/agent-settings.custom-providers'
import { Route as ErrorPagesErrorPageLoadFailedRouteImport } from './routes/_error-pages/error.page-load-failed'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAppRouteRoute = InternalAppRouteRouteImport.update({
  id: '/_internal-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffReviewAgentInstanceIdRoute =
  DiffReviewAgentInstanceIdRouteImport.update({
    id: '/diff-review/$agentInstanceId',
    path: '/diff-review/$agentInstanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAppHistoryRoute = InternalAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InternalAppRouteRoute,
} as any)
const InternalAppDownloadsRoute = InternalAppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => InternalAppRouteRoute,
} as any)
const InternalAppClearDataRoute = InternalAppClearDataRouteImport.update({
  id: '/clear-data',
  path: '/clear-data',
  getParentRoute: () => InternalAppRouteRoute,
} as any)
const InternalAppBrowsingSettingsRoute =
  InternalAppBrowsingSettingsRouteImport.update({
    id: '/browsing-settings',
    path: '/browsing-settings',
    getParentRoute: () => InternalAppRouteRoute,
  } as any)
const InternalAppAgentSettingsRoute =
  InternalAppAgentSettingsRouteImport.update({
    id: '/agent-settings',
    path: '/agent-settings',
    getParentRoute: () => InternalAppRouteRoute,
  } as any)
const InternalAppAccountRoute = InternalAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => InternalAppRouteRoute,
} as any)
const InternalAppAboutRoute = InternalAppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => InternalAppRouteRoute,
} as any)
const InternalAppBrowsingSettingsIndexRoute =
  InternalAppBrowsingSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InternalAppBrowsingSettingsRoute,
  } as any)
const InternalAppAgentSettingsIndexRoute =
  InternalAppAgentSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InternalAppAgentSettingsRoute,
  } as any)
const InternalAppBrowsingSettingsWebsitePermissionsRoute =
  InternalAppBrowsingSettingsWebsitePermissionsRouteImport.update({
    id: '/website-permissions',
    path: '/website-permissions',
    getParentRoute: () => InternalAppBrowsingSettingsRoute,
  } as any)
const InternalAppAgentSettingsModelsRoute =
  InternalAppAgentSettingsModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => InternalAppAgentSettingsRoute,
  } as any)
const InternalAppAgentSettingsCustomProvidersRoute =
  InternalAppAgentSettingsCustomProvidersRouteImport.update({
    id: '/custom-providers',
    path: '/custom-providers',
    getParentRoute: () => InternalAppAgentSettingsRoute,
  } as any)
const ErrorPagesErrorPageLoadFailedRoute =
  ErrorPagesErrorPageLoadFailedRouteImport.update({
    id: '/_error-pages/error/page-load-failed',
    path: '/error/page-load-failed',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/about': typeof InternalAppAboutRoute
  '/account': typeof InternalAppAccountRoute
  '/agent-settings': typeof InternalAppAgentSettingsRouteWithChildren
  '/browsing-settings': typeof InternalAppBrowsingSettingsRouteWithChildren
  '/clear-data': typeof InternalAppClearDataRoute
  '/downloads': typeof InternalAppDownloadsRoute
  '/history': typeof InternalAppHistoryRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
  '/agent-settings/custom-providers': typeof InternalAppAgentSettingsCustomProvidersRoute
  '/agent-settings/models': typeof InternalAppAgentSettingsModelsRoute
  '/browsing-settings/website-permissions': typeof InternalAppBrowsingSettingsWebsitePermissionsRoute
  '/agent-settings/': typeof InternalAppAgentSettingsIndexRoute
  '/browsing-settings/': typeof InternalAppBrowsingSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/about': typeof InternalAppAboutRoute
  '/account': typeof InternalAppAccountRoute
  '/clear-data': typeof InternalAppClearDataRoute
  '/downloads': typeof InternalAppDownloadsRoute
  '/history': typeof InternalAppHistoryRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
  '/agent-settings/custom-providers': typeof InternalAppAgentSettingsCustomProvidersRoute
  '/agent-settings/models': typeof InternalAppAgentSettingsModelsRoute
  '/browsing-settings/website-permissions': typeof InternalAppBrowsingSettingsWebsitePermissionsRoute
  '/agent-settings': typeof InternalAppAgentSettingsIndexRoute
  '/browsing-settings': typeof InternalAppBrowsingSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_internal-app': typeof InternalAppRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/_internal-app/about': typeof InternalAppAboutRoute
  '/_internal-app/account': typeof InternalAppAccountRoute
  '/_internal-app/agent-settings': typeof InternalAppAgentSettingsRouteWithChildren
  '/_internal-app/browsing-settings': typeof InternalAppBrowsingSettingsRouteWithChildren
  '/_internal-app/clear-data': typeof InternalAppClearDataRoute
  '/_internal-app/downloads': typeof InternalAppDownloadsRoute
  '/_internal-app/history': typeof InternalAppHistoryRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/_error-pages/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
  '/_internal-app/agent-settings/custom-providers': typeof InternalAppAgentSettingsCustomProvidersRoute
  '/_internal-app/agent-settings/models': typeof InternalAppAgentSettingsModelsRoute
  '/_internal-app/browsing-settings/website-permissions': typeof InternalAppBrowsingSettingsWebsitePermissionsRoute
  '/_internal-app/agent-settings/': typeof InternalAppAgentSettingsIndexRoute
  '/_internal-app/browsing-settings/': typeof InternalAppBrowsingSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/about'
    | '/account'
    | '/agent-settings'
    | '/browsing-settings'
    | '/clear-data'
    | '/downloads'
    | '/history'
    | '/diff-review/$agentInstanceId'
    | '/error/page-load-failed'
    | '/agent-settings/custom-providers'
    | '/agent-settings/models'
    | '/browsing-settings/website-permissions'
    | '/agent-settings/'
    | '/browsing-settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/about'
    | '/account'
    | '/clear-data'
    | '/downloads'
    | '/history'
    | '/diff-review/$agentInstanceId'
    | '/error/page-load-failed'
    | '/agent-settings/custom-providers'
    | '/agent-settings/models'
    | '/browsing-settings/website-permissions'
    | '/agent-settings'
    | '/browsing-settings'
  id:
    | '__root__'
    | '/_internal-app'
    | '/home'
    | '/_internal-app/about'
    | '/_internal-app/account'
    | '/_internal-app/agent-settings'
    | '/_internal-app/browsing-settings'
    | '/_internal-app/clear-data'
    | '/_internal-app/downloads'
    | '/_internal-app/history'
    | '/diff-review/$agentInstanceId'
    | '/_error-pages/error/page-load-failed'
    | '/_internal-app/agent-settings/custom-providers'
    | '/_internal-app/agent-settings/models'
    | '/_internal-app/browsing-settings/website-permissions'
    | '/_internal-app/agent-settings/'
    | '/_internal-app/browsing-settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InternalAppRouteRoute: typeof InternalAppRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  DiffReviewAgentInstanceIdRoute: typeof DiffReviewAgentInstanceIdRoute
  ErrorPagesErrorPageLoadFailedRoute: typeof ErrorPagesErrorPageLoadFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal-app': {
      id: '/_internal-app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InternalAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-review/$agentInstanceId': {
      id: '/diff-review/$agentInstanceId'
      path: '/diff-review/$agentInstanceId'
      fullPath: '/diff-review/$agentInstanceId'
      preLoaderRoute: typeof DiffReviewAgentInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal-app/history': {
      id: '/_internal-app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof InternalAppHistoryRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/downloads': {
      id: '/_internal-app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof InternalAppDownloadsRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/clear-data': {
      id: '/_internal-app/clear-data'
      path: '/clear-data'
      fullPath: '/clear-data'
      preLoaderRoute: typeof InternalAppClearDataRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/browsing-settings': {
      id: '/_internal-app/browsing-settings'
      path: '/browsing-settings'
      fullPath: '/browsing-settings'
      preLoaderRoute: typeof InternalAppBrowsingSettingsRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/agent-settings': {
      id: '/_internal-app/agent-settings'
      path: '/agent-settings'
      fullPath: '/agent-settings'
      preLoaderRoute: typeof InternalAppAgentSettingsRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/account': {
      id: '/_internal-app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof InternalAppAccountRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/about': {
      id: '/_internal-app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof InternalAppAboutRouteImport
      parentRoute: typeof InternalAppRouteRoute
    }
    '/_internal-app/browsing-settings/': {
      id: '/_internal-app/browsing-settings/'
      path: '/'
      fullPath: '/browsing-settings/'
      preLoaderRoute: typeof InternalAppBrowsingSettingsIndexRouteImport
      parentRoute: typeof InternalAppBrowsingSettingsRoute
    }
    '/_internal-app/agent-settings/': {
      id: '/_internal-app/agent-settings/'
      path: '/'
      fullPath: '/agent-settings/'
      preLoaderRoute: typeof InternalAppAgentSettingsIndexRouteImport
      parentRoute: typeof InternalAppAgentSettingsRoute
    }
    '/_internal-app/browsing-settings/website-permissions': {
      id: '/_internal-app/browsing-settings/website-permissions'
      path: '/website-permissions'
      fullPath: '/browsing-settings/website-permissions'
      preLoaderRoute: typeof InternalAppBrowsingSettingsWebsitePermissionsRouteImport
      parentRoute: typeof InternalAppBrowsingSettingsRoute
    }
    '/_internal-app/agent-settings/models': {
      id: '/_internal-app/agent-settings/models'
      path: '/models'
      fullPath: '/agent-settings/models'
      preLoaderRoute: typeof InternalAppAgentSettingsModelsRouteImport
      parentRoute: typeof InternalAppAgentSettingsRoute
    }
    '/_internal-app/agent-settings/custom-providers': {
      id: '/_internal-app/agent-settings/custom-providers'
      path: '/custom-providers'
      fullPath: '/agent-settings/custom-providers'
      preLoaderRoute: typeof InternalAppAgentSettingsCustomProvidersRouteImport
      parentRoute: typeof InternalAppAgentSettingsRoute
    }
    '/_error-pages/error/page-load-failed': {
      id: '/_error-pages/error/page-load-failed'
      path: '/error/page-load-failed'
      fullPath: '/error/page-load-failed'
      preLoaderRoute: typeof ErrorPagesErrorPageLoadFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InternalAppAgentSettingsRouteChildren {
  InternalAppAgentSettingsCustomProvidersRoute: typeof InternalAppAgentSettingsCustomProvidersRoute
  InternalAppAgentSettingsModelsRoute: typeof InternalAppAgentSettingsModelsRoute
  InternalAppAgentSettingsIndexRoute: typeof InternalAppAgentSettingsIndexRoute
}

const InternalAppAgentSettingsRouteChildren: InternalAppAgentSettingsRouteChildren =
  {
    InternalAppAgentSettingsCustomProvidersRoute:
      InternalAppAgentSettingsCustomProvidersRoute,
    InternalAppAgentSettingsModelsRoute: InternalAppAgentSettingsModelsRoute,
    InternalAppAgentSettingsIndexRoute: InternalAppAgentSettingsIndexRoute,
  }

const InternalAppAgentSettingsRouteWithChildren =
  InternalAppAgentSettingsRoute._addFileChildren(
    InternalAppAgentSettingsRouteChildren,
  )

interface InternalAppBrowsingSettingsRouteChildren {
  InternalAppBrowsingSettingsWebsitePermissionsRoute: typeof InternalAppBrowsingSettingsWebsitePermissionsRoute
  InternalAppBrowsingSettingsIndexRoute: typeof InternalAppBrowsingSettingsIndexRoute
}

const InternalAppBrowsingSettingsRouteChildren: InternalAppBrowsingSettingsRouteChildren =
  {
    InternalAppBrowsingSettingsWebsitePermissionsRoute:
      InternalAppBrowsingSettingsWebsitePermissionsRoute,
    InternalAppBrowsingSettingsIndexRoute:
      InternalAppBrowsingSettingsIndexRoute,
  }

const InternalAppBrowsingSettingsRouteWithChildren =
  InternalAppBrowsingSettingsRoute._addFileChildren(
    InternalAppBrowsingSettingsRouteChildren,
  )

interface InternalAppRouteRouteChildren {
  InternalAppAboutRoute: typeof InternalAppAboutRoute
  InternalAppAccountRoute: typeof InternalAppAccountRoute
  InternalAppAgentSettingsRoute: typeof InternalAppAgentSettingsRouteWithChildren
  InternalAppBrowsingSettingsRoute: typeof InternalAppBrowsingSettingsRouteWithChildren
  InternalAppClearDataRoute: typeof InternalAppClearDataRoute
  InternalAppDownloadsRoute: typeof InternalAppDownloadsRoute
  InternalAppHistoryRoute: typeof InternalAppHistoryRoute
}

const InternalAppRouteRouteChildren: InternalAppRouteRouteChildren = {
  InternalAppAboutRoute: InternalAppAboutRoute,
  InternalAppAccountRoute: InternalAppAccountRoute,
  InternalAppAgentSettingsRoute: InternalAppAgentSettingsRouteWithChildren,
  InternalAppBrowsingSettingsRoute:
    InternalAppBrowsingSettingsRouteWithChildren,
  InternalAppClearDataRoute: InternalAppClearDataRoute,
  InternalAppDownloadsRoute: InternalAppDownloadsRoute,
  InternalAppHistoryRoute: InternalAppHistoryRoute,
}

const InternalAppRouteRouteWithChildren =
  InternalAppRouteRoute._addFileChildren(InternalAppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  InternalAppRouteRoute: InternalAppRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  DiffReviewAgentInstanceIdRoute: DiffReviewAgentInstanceIdRoute,
  ErrorPagesErrorPageLoadFailedRoute: ErrorPagesErrorPageLoadFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
