-- VERSION: 1

CREATE TABLE IF NOT EXISTS meta(
    key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY,
    value LONGVARCHAR
);

CREATE TABLE IF NOT EXISTS origin_thumbnails(
    id INTEGER PRIMARY KEY,
    origin TEXT NOT NULL UNIQUE,
    image_data BLOB NOT NULL,
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    last_updated INTEGER NOT NULL DEFAULT 0,
    last_accessed INTEGER NOT NULL DEFAULT 0
);

