declare const __APP_RELEASE_CHANNEL__: 'dev' | 'prerelease' | 'release';
declare const __APP_BASE_NAME__: string;
declare const __APP_NAME__: string;
declare const __APP_BUNDLE_ID__: string;
declare const __APP_VERSION__: string;
declare const __APP_AUTHOR__: string;
declare const __APP_COPYRIGHT__: string;
declare const __APP_HOMEPAGE__: string;
declare const __APP_PLATFORM__: string;
declare const __APP_ARCH__: string;
